### ISSUE TITLE
[研究] 測試不同的consumer policy

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#200]
測試一：測試兩百萬個partitions在不同策略下的平衡狀況
- partitions數量
- 資料量
- topic數量

測試二：測試兩百萬個partitions在不同策略下的平衡速度
- 達到平衡需要花多少時間？
- 新增/刪除consumer後達到平衡需要多少時間?
- 新增partition後達到平衡需要多少時間?
- 平衡過程中會“停止讀取”多久？

**Comment by harryteng9527** [comment]
1/29 - 架設Kafka Cluster

建立環境時，利用專案內的
```=bash
./docker/start_broker.sh zookeeper.connect=192.168.103.80:18008
```
建立Kafka cluster時，某幾台server的VM不能正常啟動broker，但是又有幾台server的VM可以正常啟動broker`(每台VM皆在不同的Server上)`

以下為不能正常啟動broker的log:

[2022-01-29 07:42:59,471] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2022-01-29 07:42:59,623] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
	at java.base/java.util.Properties.load0(Properties.java:418)
	at java.base/java.util.Properties.load(Properties.java:407)
	at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:666)
	at kafka.Kafka$.getPropsFromArgs(Kafka.scala:52)
	at kafka.Kafka$.main(Kafka.scala:86)
	at kafka.Kafka.main(Kafka.scala)

本來想自己解決看看此IOException(Is a directory)，但解決不了

所以目前會在可以正常創建broker的server中多開幾個VM，建立200萬個partitions的環境


> `每台VM皆在不同的Server上的想法`:  為了更接近實際cluster的環境，因在同台server上創建多個VM就不會使用到網路線

**Comment by chia7712** [comment]
> 建立Kafka cluster時，某幾台server的VM不能正常啟動broker，但是又有幾台server的VM可以正常啟動broker(每台VM皆在不同的Server上)

那個「幾台」是同一台實體機嗎？

**Comment by chia7712** [comment]
另外麻煩確認一下是否用我們最新的docker image 來測試

**Comment by harryteng9527** [comment]
> 那個「幾台」是同一台實體機嗎？

不同的server(實體機)，目前有兩台server的VM可以正常創建broker

> 另外麻煩確認一下是否用我們最新的docker image 來測試

VM安裝完OS後，都是直接clone專案到VM上進行後續的部署
```=bash
git clone https://github.com/skiptests/astraea.git
```
所以應該都是使用最新的docker image

**Comment by chia7712** [comment]
> 所以應該都是使用最新的docker image

預設行為不會自動拉取最新的docker image，你可以手動更新一下

**Comment by chia7712** [comment]
> 不同的server(實體機)，目前有兩台server的VM可以正常創建broker

可否將完整的log貼上來？謝謝

**Comment by harryteng9527** [comment]
> 預設行為不會自動拉取最新的docker image，你可以手動更新一下

OK

> 可否將完整的log貼上來？

完整log:
`[2022-01-29 06:30:38,388] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2022-01-29 06:30:38,508] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
	at java.base/java.util.Properties.load0(Properties.java:418)
	at java.base/java.util.Properties.load(Properties.java:407)
	at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:666)
	at kafka.Kafka$.getPropsFromArgs(Kafka.scala:52)
	at kafka.Kafka$.main(Kafka.scala:86)
	at kafka.Kafka.main(Kafka.scala)
`
****
剛剛靈光一閃，看了一下docker版本
發現能建立broker的版本為`20.10.7`，會發生Exception的版本為`20.10.8`
然後我把20.10.8降到20.10.7就可以正常建立broker了

**Comment by chia7712** [comment]
> 然後我把20.10.8降到20.10.7就可以正常建立broker了

真假@@ 居然會在patch版本就造成破壞...

**Comment by chia7712** [comment]
可否確認一下是否真的為版本問題？例如你更新到最新`20.10.12`看看能否正常啟動？如果真的跟版本有關的話，麻煩查看一下docker release note看看可能是哪個原因

**Comment by harryteng9527** [comment]
> 更新到最新`20.10.12`看看能否正常啟動？

測試後發現不是版本的問題，剛剛透過[Docker官網](https://docs.docker.com/engine/install/ubuntu/)的步驟刪除、下載其他版本進行測試
版本依序為`20.10.7`->`20.10.12`->`20.10.8`都可以創建broker

由於可能是版本問題的選項已經移除了，所以我想了想整個建VM流程中跟docker有關的步驟

應該是我在建VM的時候，用**snap**安裝docker(下圖所示)
<img width="1047" alt="螢幕快照 2022-01-30 上午1 15 06" src="https://user-images.githubusercontent.com/90374678/151670484-3d50a39b-c516-4933-a747-e0d9fbf0397d.png">

所以導致出現IOException的錯誤，不能正常創建broker

snap的安裝log:
<img width="802" alt="螢幕快照 2022-01-30 上午1 29 21" src="https://user-images.githubusercontent.com/90374678/151671042-61279244-c2d9-42b7-bab6-8fb3cb7e0814.png">

broker無法正常創建的問題已解決，所以會繼續用五台不同的server(實體機)來架設環境
謝謝

**Comment by garyparrot** [comment]
> > 預設行為不會自動拉取最新的docker image，你可以手動更新一下
> 
> OK
> 
> > 可否將完整的log貼上來？
> 
> 完整log: `[2022-01-29 06:30:38,388] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$) [2022-01-29 06:30:38,508] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) java.io.IOException: Is a directory at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48) at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245) at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223) at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107) at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101) at java.base/java.io.InputStream.read(InputStream.java:205) at java.base/java.util.Properties$LineReader.readLine(Properties.java:502) at java.base/java.util.Properties.load0(Properties.java:418) at java.base/java.util.Properties.load(Properties.java:407) at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:666) at kafka.Kafka$.getPropsFromArgs(Kafka.scala:52) at kafka.Kafka$.main(Kafka.scala:86) at kafka.Kafka.main(Kafka.scala) `
> 
> 剛剛靈光一閃，看了一下docker版本 發現能建立broker的版本為`20.10.7`，會發生Exception的版本為`20.10.8` 然後我把20.10.8降到20.10.7就可以正常建立broker了

我剛剛也遇到一樣的問題(也是用實驗室的環境, ubuntu, 用 snap 安裝)

我研究了一下發現 snap [會把每個 app 的 /tmp 隔離](https://forum.snapcraft.io/t/accessing-tmp-from-snaps/22384)。所以我們的 `/tmp/server-xxxxx.properties` 在 docker 的角度看不見，他可能看到一個完全空的 `/tmp` 資料夾。然後 `-v /tmp/server-xxxxx.properties:/tmp/broker.properties:ro` 的時候 docker 發現那個檔案不存在，當做要 mount 資料夾很自然的把稱作 `/tmp/server-xxxxx.properties` 的這個不存在的資料夾建立起來了，然後 Kafka 就壞了。

如果把 `server-xxxxx.properties` 放到其他資料夾(e.g. user home) 進行 mount 的話可以動

研究這個問題的過程中我順便發現 `-v` 和 `--mount` 之間的[微妙差異](https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior)

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.
>
>If you use --mount to bind-mount a file or directory that does not yet exist on the Docker host, **Docker does not automatically create it for you, but generates an error.**

因為腳本裡面是使用 `-v` 所以當檔案不在時會建立資料夾，如果是使用 `-mount` 的話，遇到這個情況會直接報錯，我們應該會在執行的過程中得到類似下面的錯誤。

> docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/server-12345.properties.
> See 'docker run --help'.

**Comment by garyparrot** [comment]
> It would be better to keep those "tmp" files in astraea folder. We can reuse the "build" folder in astraea project. WDYT?

感覺放在 `build` folder 應該不錯

**Comment by harryteng9527** [comment]
不好意思，請問可以將實驗的環境降至150萬或是100萬個partitions嗎

**想更換partitions數量的理由**: VM記憶體資源有分配足夠，但是要測試時看到記憶體資源不足導致無法測試[發生的問題1.&2.]，但找了有點久還是找不到為什麼會出現此問題

**目前環境**:
共有五台VM，創建的規格如下
1. `16core`、`200GB memory`，開22台brokers
2. `4core`、`40GB memory`，開2台brokers以及1台Zookeeper
3. `20core`、`350GB memory`，開37台brokers
4. `4core`、`50GB memory`，開5台brokers
5. `8core`、`120GB memory`，開12台brokers

共 78 台brokers， 1 台Zookeeper

每一台brokers的參數只有改動-Xmx，如下:
```
env HEAP_OPTS="-Xmx8G -Xms2G"  ./docker/start_broker.sh zookeeper.connect=192.168.103.69:17982
```

**發生的問題**:
1. 順利的創立200萬個partitions後，利用Kafka script查看目前叢集的topic時，會出現OutOfMemory的error，如下圖
![script error](https://user-images.githubusercontent.com/90374678/154936414-cdbd9d4e-222c-4b22-87f8-7b4c8ea6ea72.png)
根據error message以及上網查詢的結果，應該是記憶體不足的問題
但是看了VM的資源使用量、broker的資源使用量後(用docker stats containerID查看)，看起來都是足夠的，且brokers也都沒有shut down

2. 順利的創立200萬個partitions後，開啟consumer消費叢集資料時，會出現`SyncGroup`的error，如下圖
![consumer error](https://user-images.githubusercontent.com/90374678/154937173-253a7aa3-9381-41fb-baf1-c6d4088166d6.png)
 
3. 建立broker時，試了多種不同的`-Xmx設置`，從8G~20G都有，只有在`"-Xmx8G"`的時候可以創建到約200萬個partitions，`"-Xmx10G"`大約170萬個partitions，再上去至`"-Xmx16G"`時，只能夠創建100～120萬個partitions
partitions若超過上述可創建的最大值，broker會因為`OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fc8002ff000, 16384, 0) failed; error='Not enough space' (errno=12)` 的錯誤或是`Caused by: java.lang.OutOfMemoryError: Map failed`直接將broker關閉

**Comment by chia7712** [comment]
> 不好意思，請問可以將實驗的環境降至150萬或是100萬個partitions嗎

這個實驗有一個重點是： 讓我們知道Kafka在讀寫端會不會遇到擴充的瓶頸，其中一個很常討論的瓶頸就是 - partitions太多會不會出問題？如果會出問題，那是在哪一個階段會出問題？

要麻煩你看看能否回答上述兩個問題，能回答的話應該會讓你做後續「大規模的consumer balancer」更有感覺

**Comment by chia7712** [comment]
> 會，partitions數目太多會發生下列問題:
Server端以及Client端需使用的memory更多
因為一直增加partitions數量未必會增加效率，有可能consumer的數目過少，速度提昇不上去，而要增加consumer數量勢必就要消耗Client端的記憶體以及thread
高頻率的讀寫，使得page cache需求大
File descriptor的cost
因為每一個partition都會對應到log資料夾內的一個目錄，每個broker會open .log file，但我覺得這個的記憶體使用量不會太高
增加End-to-End的latency
若partition replica數量大於1時，follower會需要去同步leader的資料，而每一個broker只分配一個thread去執行同步的工作，故commit時間拉長
增加Unavailability
因為partition的leader、follower分佈在broker中，若有broker因為某種因素而shut down，則該broker上的partition都會不可用

這些應該是網路查來的資訊吧，這幾個“隱憂”比較大方向。可能要專注在比較細節的地方，例如，

1. 當producer面對一個有成千上萬partitions的叢集時，在寫入資料時會不會出問題（例如要拉cluster資訊的時候會有明顯的延遲）
2. 當叢集要維護成千上萬的partitions時，付出了多少代價（例如記憶體常駐用量多少？會不會特別高？open file開很高會怎樣）
3. 當consumer要拉一個成千上萬的partitions時的問題會在哪裡？

**Comment by harryteng9527** [comment]
> 這些應該是網路查來的資訊吧

對，我查了好幾天，怎麼查都是這些資訊，且也沒有頭緒找出目前是哪個階段發生問題，所以只好把這些先放上來

**Comment by chia7712** [comment]
> 且也沒有頭緒找出目前是哪個階段發生問題

可以試試看寫一隻小程式，然後用JMC之類的工具去觀察程式執行的狀況，這部分 @wycccccc 應該已經有一些經驗了，可以問一下學長

**Comment by chia7712** [comment]
後續由https://github.com/skiptests/astraea/issues/431 追蹤
